# Generated by Django 5.1.6 on 2025-03-05 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Title must contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Price should not exceed 10,000.', validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(help_text='Rating must be between 0 and 5.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Title must contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
